"""empty message

Revision ID: e3c321ab1230
Revises: 
Create Date: 2026-01-06 16:36:28.293989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c321ab1230'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teksty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=255), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wpisy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tekst_id', sa.Integer(), nullable=False),
    sa.Column('rola', sa.String(length=100), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tekst_id'], ['Teksty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Wpisy')
    op.drop_table('Teksty')
    # ### end Alembic commands ###
